services:
  backend:
    build:
      context: .
      dockerfile: service/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - hf_cache:/root/.cache/huggingface  
 
  frontend:
    build:
      context: .
      dockerfile: service/frontend/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  hf_cache:
